// This file should be replaced with actual code for the generated by the generator.
//
// Files in the targets/ directory are those generated by tests, and likely should
// be removed on tear down.
//
// This file is here also to force git to ship the directory
// structure, which it doesn't do if the directory is empty